### ISSUE TITLE
Unwrapped Code

### ISSUE THREAD

**Issue by jorgelina-aydarpaz** [antonscheffer/APEX2XLSX#5]
Hi,

This is not really an issue, but, is there any chance to obtain the unwrapped code of the pl/sql?
I would like to use it, but for a classic report, however this only works for IRs, this means I would have to alter it in order to allow classic reports, or at least use a similar procedure for it.
Do you think is possible?
Thank you

**Comment by antonscheffer** [comment]
I thought this plugin should also work on classic reports, not quite sure because I've not looked for several years. The code is not wrapped but compressed. If it's not compressed it won't fit in the max size for plsql code of a plugin. Code to uncompress it is inside the plugin, you should be able to figure that out yourself.
